apiVersion: "mlkube.io/v1beta1"
kind: TfJob
metadata:
  name: whatev
spec:
  replica_specs:
    - replicas: 1
      tf_port: 2222
      tf_replica_type: MASTER
      template:
        spec:
          containers:
            - image: wbuchwalter/helm-tf:hyper-param-sweep
              command:
                - python
                - main.py
              name: tensorflow
              resources:
                limits:
                  alpha.kubernetes.io/nvidia-gpu: 1
          restartPolicy: OnFailure
