apiVersion: "mlkube.io/v1beta1"
kind: "TfJob"
metadata:
  name: "example-job"
spec:
  replica_specs:
    - replicas: 1
      tf_port: 2222
      tf_replica_type: MASTER
      template:
        spec:
          containers:
            - image: wbuchwalter/helm-tf:distributed-tf-cpu
              name: tensorflow
              command:
                - python
                - main.py
                - --lr
                - "0.005"
                - --epochs
                - "200"
                - --batch_size
                - "1"
          restartPolicy: OnFailure
    - replicas: 3
      tf_port: 2222
      tf_replica_type: WORKER
      template:
        spec:
          containers:
            - image: wbuchwalter/helm-tf:distributed-tf-cpu
              name: tensorflow
          restartPolicy: OnFailure